In [3]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
df = spark.read.csv('./melb_data.csv', header=True, inferSchema=True, sep=',')
df.show()

+----------+-------------------+-----+----+---------+------+-------+----------+--------+--------+--------+--------+---+--------+------------+---------+-----------+---------+----------+--------------------+-------------+
|    Suburb|            Address|Rooms|Type|    Price|Method|SellerG|      Date|Distance|Postcode|Bedroom2|Bathroom|Car|Landsize|BuildingArea|YearBuilt|CouncilArea|Lattitude|Longtitude|          Regionname|Propertycount|
+----------+-------------------+-----+----+---------+------+-------+----------+--------+--------+--------+--------+---+--------+------------+---------+-----------+---------+----------+--------------------+-------------+
|Abbotsford|       85 Turner St|    2|   h|1480000.0|     S| Biggin| 3/12/2016|     2.5|  3067.0|     2.0|     1.0|1.0|   202.0|        NULL|     NULL|      Yarra| -37.7996|  144.9984|Northern Metropol...|       4019.0|
|Abbotsford|    25 Bloomburg St|    2|   h|1035000.0|     S| Biggin| 4/02/2016|     2.5|  3067.0|     2.0|     1.0|0.0|   156.0|        79.0|   1900.0|      Yarra| -37.8079|  144.9934|Northern Metropol...|       4019.0|
|Abbotsford|       5 Charles St|    3|   h|1465000.0|    SP| Biggin| 4/03/2017|     2.5|  3067.0|     3.0|     2.0|0.0|   134.0|       150.0|   1900.0|      Yarra| -37.8093|  144.9944|Northern Metropol...|       4019.0|
|Abbotsford|   40 Federation La|    3|   h| 850000.0|    PI| Biggin| 4/03/2017|     2.5|  3067.0|     3.0|     2.0|1.0|    94.0|        NULL|     NULL|      Yarra| -37.7969|  144.9969|Northern Metropol...|       4019.0|
|Abbotsford|        55a Park St|    4|   h|1600000.0|    VB| Nelson| 4/06/2016|     2.5|  3067.0|     3.0|     1.0|2.0|   120.0|       142.0|   2014.0|      Yarra| -37.8072|  144.9941|Northern Metropol...|       4019.0|
|Abbotsford|     129 Charles St|    2|   h| 941000.0|     S| Jellis| 7/05/2016|     2.5|  3067.0|     2.0|     1.0|0.0|   181.0|        NULL|     NULL|      Yarra| -37.8041|  144.9953|Northern Metropol...|       4019.0|
|Abbotsford|       124 Yarra St|    3|   h|1876000.0|     S| Nelson| 7/05/2016|     2.5|  3067.0|     4.0|     2.0|0.0|   245.0|       210.0|   1910.0|      Yarra| -37.8024|  144.9993|Northern Metropol...|       4019.0|
|Abbotsford|      98 Charles St|    2|   h|1636000.0|     S| Nelson| 8/10/2016|     2.5|  3067.0|     2.0|     1.0|2.0|   256.0|       107.0|   1890.0|      Yarra|  -37.806|  144.9954|Northern Metropol...|       4019.0|
|Abbotsford| 6/241 Nicholson St|    1|   u| 300000.0|     S| Biggin| 8/10/2016|     2.5|  3067.0|     1.0|     1.0|1.0|     0.0|        NULL|     NULL|      Yarra| -37.8008|  144.9973|Northern Metropol...|       4019.0|
|Abbotsford|      10 Valiant St|    2|   h|1097000.0|     S| Biggin| 8/10/2016|     2.5|  3067.0|     3.0|     1.0|2.0|   220.0|        75.0|   1900.0|      Yarra|  -37.801|  144.9989|Northern Metropol...|       4019.0|
|Abbotsford| 411/8 Grosvenor St|    2|   u| 700000.0|    VB| Jellis|12/11/2016|     2.5|  3067.0|     2.0|     2.0|1.0|     0.0|        NULL|     NULL|      Yarra|  -37.811|  145.0067|Northern Metropol...|       4019.0|
|Abbotsford|    40 Nicholson St|    3|   h|1350000.0|    VB| Nelson|12/11/2016|     2.5|  3067.0|     3.0|     2.0|2.0|   214.0|       190.0|   2005.0|      Yarra| -37.8085|  144.9964|Northern Metropol...|       4019.0|
|Abbotsford|123/56 Nicholson St|    2|   u| 750000.0|     S| Biggin|12/11/2016|     2.5|  3067.0|     2.0|     2.0|1.0|     0.0|        94.0|   2009.0|      Yarra| -37.8078|  144.9965|Northern Metropol...|       4019.0|
|Abbotsford|      45 William St|    2|   h|1172500.0|     S| Biggin|13/08/2016|     2.5|  3067.0|     2.0|     1.0|1.0|   195.0|        NULL|     NULL|      Yarra| -37.8084|  144.9973|Northern Metropol...|       4019.0|
|Abbotsford| 7/20 Abbotsford St|    1|   u| 441000.0|    SP|   Greg|14/05/2016|     2.5|  3067.0|     1.0|     1.0|1.0|     0.0|        NULL|     NULL|      Yarra| -37.8016|  144.9988|Northern Metropol...|       4019.0|
|Abbotsford|      16 William St|    2|   h|1310000.0|     S| Jellis|15/10/2016|     2.5|  3067.0|     2.0|     1.0|2.0|   238.0|        97.0|   1890.0|      Yarra|  -37.809|  144.9976|Northern Metropol...|       4019.0|
|Abbotsford|        42 Henry St|    3|   h|1200000.0|     S| Jellis|16/07/2016|     2.5|  3067.0|     3.0|     2.0|1.0|   113.0|       110.0|   1880.0|      Yarra| -37.8056|   144.993|Northern Metropol...|       4019.0|
|Abbotsford|        78 Yarra St|    3|   h|1176500.0|     S| LITTLE|16/07/2016|     2.5|  3067.0|     2.0|     1.0|1.0|   138.0|       105.0|   1890.0|      Yarra| -37.8021|  144.9965|Northern Metropol...|       4019.0|
|Abbotsford|   196 Nicholson St|    3|   h| 955000.0|     S|Collins|17/09/2016|     2.5|  3067.0|     3.0|     1.0|0.0|   183.0|        NULL|     NULL|      Yarra| -37.8022|  144.9975|Northern Metropol...|       4019.0|
|Abbotsford|      42 Valiant St|    2|   h| 890000.0|     S| Biggin|17/09/2016|     2.5|  3067.0|     2.0|     1.0|1.0|   150.0|        73.0|   1985.0|      Yarra| -37.8011|  145.0004|Northern Metropol...|       4019.0|
+----------+-------------------+-----+----+---------+------+-------+----------+--------+--------+--------+--------+---+--------+------------+---------+-----------+---------+----------+--------------------+-------------+
only showing top 20 rows

# Calculating Cardinality

In [12]:
from pyspark.sql.functions import approx_count_distinct, countDistinct

def cardinality_calculation(df, cut_off=1):
    cardinality = df.select(*[approx_count_distinct(c).alias(c) for c in df.columns])
    
    ## convert to pandas for efficient calculations
    final_cardinality_df = cardinality.toPandas().transpose()
    final_cardinality_df.reset_index(inplace=True) 
    final_cardinality_df.rename(columns={0:'Cardinality'}, inplace=True) 
    
    #select variables with cardinality of 1
    vars_selected = final_cardinality_df['index'][final_cardinality_df['Cardinality'] <= cut_off] 
    
    return final_cardinality_df, vars_selected

cardinality_df, selected_cardinality_vars = cardinality_calculation(df)

In [13]:
cardinality_df

            index  Cardinality
0          Suburb          318
1         Address        14421
2           Rooms            9
3            Type            3
4           Price         2328
5          Method            5
6         SellerG          277
7            Date           58
8        Distance          207
9        Postcode          207
10       Bedroom2           12
11       Bathroom            9
12            Car           11
13       Landsize         1432
14   BuildingArea          599
15      YearBuilt          145
16    CouncilArea           34
17      Lattitude         6297
18     Longtitude         7057
19     Regionname            8
20  Propertycount          313

In [14]:
selected_cardinality_vars

Series([], Name: index, dtype: object)

Because there's no variables with Cardinality of 1, we didn't reject any variables

# Check Missin Value

In [16]:
import pandas as pd

In [20]:
pandasDF = df.toPandas()

In [21]:
pandasDF

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,None,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,None,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,None,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,None,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,None,-37.81188,144.88449,Western Metropolitan,6543.0

In [22]:
pandasDF.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

We will reject any variable with more than 45% missing value

In [46]:
def reject_missing(df, percentage) :
    i = 0
    rejected_vars = pd.DataFrame(columns=['var_name', 'missing_value'])
    length = len(df)
    for c in df.columns :
        if pd.isnull(df[c]).sum()/length > percentage :
            i =+ 1
            rejected_vars.loc[i] = [c, pd.isnull(df[c]).sum()]
    return rejected_vars

In [47]:
reject_missing(pandasDF, 0.45)

       var_name  missing_value
1  BuildingArea           6450