In [1]:
from faker import Faker
import pandas as pd

In [3]:
fake = Faker()

In [14]:
def generator() :
    i = fake.random_int(min=1, max=9999)
    # Create Unique ID with Format : JKT-0001
    unique_id = f'JKT-{i:04}'
    # Create Fake Data Consisting of Age, Gender, Math Score, Reading Score, Writing Score, and Lunch Type (Standard or Free/Reduced).
    age = fake.random_int(min=15, max=18)
    Gender = fake.random_element(elements=('Male', 'Female'))
    Math_Score = fake.random_int(min=0, max=100)
    Reading_Score = fake.random_int(min=0, max=100)
    Writing_Score = fake.random_int(min=0, max=100)
    Lunch = fake.random_element(elements=('Standard', 'Free/Reduced'))

    # Create a List to Store the Data
    data = [unique_id, age, Gender, Math_Score, Reading_Score, Writing_Score, Lunch]
    return data

In [15]:
generator()

['JKT-7630', 16, 'Female', 3, 83, 85, 'Free/Reduced']

In [19]:
# Create a dataframe to store the data
df = pd.DataFrame(columns=["unique_id", "age", "Gender", "Math_Score", "Reading_Score", "Writing_Score", "Lunch"])
df

Empty DataFrame
Columns: [unique_id, age, Gender, Math_Score, Reading_Score, Writing_Score, Lunch]
Index: []

In [21]:
for i in range(10000):
    df.loc[i] = generator()

In [22]:
df

,unique_id,age,Gender,Math_Score,Reading_Score,Writing_Score,Lunch
0,JKT-2591,18,Female,31,67,71,Standard
1,JKT-8866,15,Male,19,33,50,Standard
2,JKT-0825,17,Female,83,60,44,Standard
3,JKT-9008,18,Female,78,3,82,Standard
4,JKT-5989,18,Female,7,21,62,Standard
...,...,...,...,...,...,...,...
39283,JKT-7323,16,Male,58,65,9,Free/Reduced
39284,JKT-5275,17,Male,35,21,40,Free/Reduced
39285,JKT-3760,15,Male,0,88,92,Standard
39286,JKT-3994,18,Female,92,58,99,Free/Reduced
39287,JKT-7680,17,Male,49,61,72,Free/Reduced

In [23]:
# Save the dataframe to csv file
df.to_csv('fake-data.csv', index=False)